JACKDAW = fe80::12:13ff:fe14:1516
BOARD = fe80::00ff:fe00:0001
#CONTIKI = $(shell echo $$HOME)/es-projekt/contiki
CONTIKI = ../../../platform/contiki

all:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board avr-atmega128rfa1-write.hex $(MAKEOPTS) \
	                    CONFIG_USE_DERFMEGA128=1 \
	                    PLATFORM_CONTIKI_SDDS_SEND_ADDRESSS="$(JACKDAW)"
	$(MAKE) -f Makefile BUILD=linux test-write $(MAKEOPTS) \
	                    PLATFORM_LINUX_SDDS_LISTEN_ADDRESS="$(JACKDAW)%usb0" \
	                    PLATFORM_LINUX_SDDS_SEND_ADDRESS="$(BOARD)%usb0"

flash:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board flash $(MAKEOPTS)

debug:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board debug $(MAKEOPTS)

clean:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board clean
	$(MAKE) -f Makefile BUILD=linux clean
