#ifndef TWI_TYPE_H_INCLUDED
#define TWI_TYPE_H_INCLUDED

enum twi_type
{
	TWI_TYPE_TRANSMIT_ADDRESS = 1,
	TWI_TYPE_RECEIVE_ADDRESS,
	TWI_TYPE_TRANSMIT_DATA,
	TWI_TYPE_RECEIVE_DATA,
	TWI_TYPE_START,
	TWI_TYPE_STOP
};

#endif
