#define PLATFORM_LINUX_SDDS_IFACE					"usb0"
#define PLATFORM_LINUX_SDDS_IP_ADDRESS 				"fe80::12:13ff:fe14:2323"
#define PLATFORM_LINUX_SDDS_LISTEN_ADDRESS			PLATFORM_LINUX_SDDS_IP_ADDRESS"%"PLATFORM_LINUX_SDDS_IFACE
#define PLATFORM_LINUX_SDDS_SEND_ADDRESS			PLATFORM_LINUX_SDDS_IP_ADDRESS"%"PLATFORM_LINUX_SDDS_IFACE

#define PLATFORM_LINUX_SDDS_PROTOCOL				AF_INET6
#define PLATFORM_LINUX_SDDS_PORT					23234
