#define FEATURE_SDDS_MULTICAST_ENABLED
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED

#define FEATURE_SDDS_TRACING_ENABLED
#define FEATURE_SDDS_TRACING_RECV_PAKET
//#define FEATURE_SDDS_TRACING_PROCESS_FRAME
//#define FEATURE_SDDS_TRACING_HISTORY_ENQUEUE
//#define FEATURE_SDDS_TRACING_DATA_WRITE
//#define FEATURE_SDDS_TRACING_HISTORY_DEQUEUE
//#define FEATURE_SDDS_TRACING_SEND_PAKET
#define FEATURE_SDDS_TRACING_SIGNAL_RECV_PAKET
#define FEATURE_SDDS_TRACING_SIGNAL_SEND_PAKET


#define SDDS_NET_MAX_LOCATOR_COUNT 					20
#define SDDS_DISCOVERY_RECEIVE_TIMER				1
#define SDDS_DISCOVERY_PARTICIPANT_TIMER		10
#define SDDS_DISCOVERY_PUBLICATION_TIMER		60
#define SDDS_DISCOVERY_TOPIC_TIMER					0



/*#define SDDS_NET_MAX_LOCATOR_COUNT 					20
#define SDDS_DISCOVERY_RECEIVE_TIMER				1
#define SDDS_DISCOVERY_PARTICIPANT_TIMER			1
#define SDDS_DISCOVERY_PUBLICATION_TIMER			1
#define SDDS_DISCOVERY_TOPIC_TIMER					0*/

//#define UTILS_DEBUG
