
#define _MULTICAST
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED

#define SDDS_NET_MAX_LOCATOR_COUNT 					20
#define SDDS_DISCOVERY_RECEIVE_TIMER				1
#define SDDS_DISCOVERY_PARTICIPANT_TIMER			10
#define SDDS_DISCOVERY_PUBLICATION_TIMER			60
#define SDDS_DISCOVERY_TOPIC_TIMER					0

/*#define PLATFORM_AUTOBEST_SDDS_IP_ADDRESS 			"fe80::201:2ff:fe03:405" 
#define PLATFORM_AUTOBEST_SDDS_LISTEN_ADDRESS		PLATFORM_AUTOBEST_SDDS_IP_ADDRESS
#define PLATFORM_AUTOBEST_SDDS_SEND_ADDRESS			PLATFORM_AUTOBEST_SDDS_IP_ADDRESS
#define PLATFORM_AUTOBEST_SDDS_PROTOCOL				AF_INET6

#define SDDS_BUILTIN_MULTICAST_ADDRESS				"ff02::10"
#define SDDS_BUILTIN_PARTICIPANT_ADDRESS			"ff02::20"
#define SDDS_BUILTIN_SUB_PUB_ADDRESS				"ff02::30"
#define SDDS_BUILTIN_TOPIC_ADDRESS					"ff02::50"*/

/*#define PLATFORM_AUTOBEST_SDDS_IP_ADDRESS 			"10.18.48.178"
#define PLATFORM_AUTOBEST_SDDS_LISTEN_ADDRESS		PLATFORM_AUTOBEST_SDDS_IP_ADDRESS
#define PLATFORM_AUTOBEST_SDDS_SEND_ADDRESS			PLATFORM_AUTOBEST_SDDS_IP_ADDRESS
#define PLATFORM_AUTOBEST_SDDS_PROTOCOL				AF_INET*/

#define UTILS_DEBUG
