APPLICATION_NAME = linux_location_tracking_sim

export APPLICATION_NAME

all:
	$(MAKE) -f Makefile_2nd_lvl.mk $(APPLICATION_NAME) $(MAKEOPTS)

code:
	$(MAKE) -f Makefile_2nd_lvl.mk code

clean:
	$(MAKE) -f Makefile_2nd_lvl.mk clean
