#ifndef FEATURE_SDDS_MULTICAST_ENABLED
#define FEATURE_SDDS_MULTICAST_ENABLED
#endif
#ifndef FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#endif
#ifndef FEATURE_SDDS_DISCOVERY_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED
#endif
#ifndef SDDS_NET_MAX_BUF_SIZE
#define SDDS_NET_MAX_BUF_SIZE 128
#endif
#ifndef SDDS_QOS_HISTORY_DEPTH
#define SDDS_QOS_HISTORY_DEPTH 3
#endif
#ifndef SDDS_NET_MAX_LOCATOR_COUNT
#define SDDS_NET_MAX_LOCATOR_COUNT 10
#endif
#ifndef SDDS_DISCOVERY_RECEIVE_TIMER
#define SDDS_DISCOVERY_RECEIVE_TIMER 1
#endif
#ifndef SDDS_DISCOVERY_PARTICIPANT_TIMER
#define SDDS_DISCOVERY_PARTICIPANT_TIMER 10
#endif
#ifndef SDDS_DISCOVERY_PUBLICATION_TIMER
#define SDDS_DISCOVERY_PUBLICATION_TIMER 10
#endif
#ifndef SDDS_DISCOVERY_TOPIC_TIMER
#define SDDS_DISCOVERY_TOPIC_TIMER 0
#endif
