#define FEATURE_SDDS_MULTICAST_ENABLED
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED

#define SDDS_NET_MAX_BUF_SIZE						128
#define SDDS_NET_MAX_LOCATOR_COUNT 					10
#define SDDS_DISCOVERY_RECEIVE_TIMER				1
#define SDDS_DISCOVERY_PARTICIPANT_TIMER			60
#define SDDS_DISCOVERY_PUBLICATION_TIMER			120
#define SDDS_DISCOVERY_TOPIC_TIMER					0

//#define SDDS_QOS_LATENCYBUDGET
#define SDDS_QOS_DW_LATBUD 10000
#define SDDS_QOS_DW_COMM 1000
#define SDDS_QOS_DW_READ 1000

//#define UTILS_DEBUG
