#define PLATFORM_RTOS_SDDS_IFACE					""
#define PLATFORM_RTOS_SDDS_IP_ADDRESS 				"192.168.178.21"
#define PLATFORM_RTOS_SDDS_LISTEN_ADDRESS			PLATFORM_RTOS_SDDS_IP_ADDRESS
#define PLATFORM_RTOS_SDDS_SEND_ADDRESS				PLATFORM_RTOS_SDDS_IP_ADDRESS

#define PLATFORM_RTOS_SDDS_PROTOCOL					AF_INET4
#define PLATFORM_RTOS_SDDS_PORT						23234

#define HW_ADDR0									0xE1
#define HW_ADDR1									0x00
#define HW_ADDR2									0x00
#define HW_ADDR3									0x00
#define HW_ADDR4									0x42
#define HW_ADDR5									0x42
