SDDS_TOPDIR := ../..

SDDS_OBJDIR := objs-riot
TARGET := riot
SDDS_PLATFORM := riot
SDDS_ARCH := x86

RIOT_OBJDIR := bin


DATASTRUCTURES_FILE := datastructures

export LOCAL_CONSTANTS :=  local_constants.h

IMPL_DEPEND_OBJS = $(SDDS_OBJDIR)/riot_sdds_impl.o
ALL_OBJS += $(IMPL_DEPEND_OBJS)
ALL_OBJS += $(SDDS_OBJDIR)/sdds.o


ifneq ($(PLATFORM_RIOT_SDDS_PORT),)
  CFLAGS += -DPLATFORM_RIOT_SDDS_PORT=$(PLATFORM_RIOT_SDDS_PORT)
endif
ifneq ($(PLATFORM_RIOT_SDDS_PROTOCOL),)
  CFLAGS += -DPLATFORM_RIOT_SDDS_PROTOCOL=$(PLATFORM_RIOT_SDDS_PROTOCOL)
endif
ifneq ($(PLATFORM_RIOT_SDDS_LISTEN_ADDRESS),)
  CFLAGS += -DPLATFORM_RIOT_SDDS_LISTEN_ADDRESS=\"$(PLATFORM_RIOT_SDDS_LISTEN_ADDRESS)\"
endif
#ifneq ($(SDDS_LINUX_SEND_ADDRESS),)
ifneq ($(PLATFORM_RIOT_SDDS_SEND_ADDRESS),)
	CFLAGS += -DPLATFORM_RIOT_SDDS_SEND_ADDRESS=\"$(PLATFORM_RIOT_SDDS_SEND_ADDRESS)\"
endif



export SDDS_CONSTANTS_FILE := gen_constants.h
#ALL_OBJS += $(SDDS_CONSTANTS_FILE)
include $(SDDS_TOPDIR)/sdds.mk

export BOARD := native
export RIOTBASE ?= $(RIOT)
export CPU := $(SDDS_ARCH)
export WERROR := 0
export QUIET ?= 1
USEMODULE += auto_init 
USEMODULE += defaulttransceiver
USEMODULE += udp
USEMODULE += vtimer


export APPLICATION := $(APPLICATION_NAME)
APPDEPS += $(LOCAL_CONSTANTS) $(SDDS_OBJDIR)/sdds.o $(SDDS_OBJS) $(IMPL_DEPEND_OBJS) $(DATA_DEPEND_OBJS) riot_sdds_impl.c riot_sdds_impl.h
APPDEPS += $(SDDS_CONSTANTS_FILE)

LINKFLAGS += $(abspath $(SDDS_OBJS)) 


export APPDEPS


INCLUDES += $(wildcard */include/)
CFLAGS += -DDEVELHELP
CFLAGS += -DUTILS_DEBUG


DATA_DEPEND_OBJS += $(SDDS_OBJDIR)/ipc-ds.o
ALL_OBJS += $(DATA_DEPEND_OBJS)

DATA_DEPEND_SRCS += $(patsubst $(SDDS_OBJDIR)/%.o,%.c,$(DATA_DEPEND_OBJS))
DATA_DEPEND_SRCS += $(patsubst $(SDDS_OBJDIR)/%.o,%.h,$(DATA_DEPEND_OBJS))
CLEAN += $(DATA_DEPEND_SRCS)

IMPL_DEPEND_SRCS += $(patsubst $(SDDS_OBJDIR)/%.o,%.c,$(IMPL_DEPEND_OBJS))
IMPL_DEPEND_SRCS += $(patsubst $(SDDS_OBJDIR)/%.o,%.h,$(IMPL_DEPEND_OBJS))
CLEAN += $(IMPL_DEPEND_SRCS)

CLEAN += $(ALL_OBJS)
CLEAN += $(patsubst %.o,%.d,$(ALL_OBJS))
CLEAN += $(SDDS_CONSTANTS_FILE)



%-ds.c %-ds.h: $(DATASTRUCTURES_FILE)
	$(shell echo  python $(SDDS_TOPDIR)/generate_ds.py $<)

%_sdds_impl.c %_sdds_impl.h: %-dds-roles $(DATASTRUCTURES_FILE) $(DATA_DEPEND_SRCS)
	$(shell echo python $(SDDS_TOPDIR)/generate_sdds.py $(<:-dds-roles=) $(DATASTRUCTURES_FILE))

all:

$(SDDS_OBJDIR):
	mkdir $(SDDS_OBJDIR)

$(LOCAL_CONSTANTS):
	touch $(LOCAL_CONSTANTS)

$(SDDS_CONSTANTS_FILE):
	touch $(SDDS_CONSTANTS_FILE)

CFLAGS += -I$(INCLUDES) 
CFLAGS += -I$(abspath ./)
CFLAGS += -O0 -ggdb3 -g


$(SDDS_OBJDIR)/%.o: %.c
	echo $(SDDS_OBJS) $(IMPL_DEPEND_OBJS) $(DATA_DEPEND_OBJS)
	$(COMPILE.c)  $(CFLAGS) -MMD $(OUTPUT_OPTION) $<

$(SDDS_OBJDIR)/%.o: %.c
	$(COMPILE.c) $(CFLAGS) -MMD $(OUTPUT_OPTION) $<

$(APPLICATION_NAME).c: $(LOCAL_CONSTANTS) $(SDDS_CONSTANTS_FILE) $(SDDS_OBJDIR) $(IMPL_DEPEND_SRCS) $(DATA_DEPEND_SRCS)

cleanlv2:
	$(RM) ./$(APPLICATION_NAME)
	$(RM) $(CLEAN)
	$(RM) $(SDDS_OBJS) $(SDDS_OBJS_DEPEND)
	$(RM) -rf $(SDDS_OBJDIR) 
	$(RM) -rf $(RIOT_OBJDIR)

-include $(patsubst %.o,%.d,$(ALL_OBJS))
include $(RIOT)/Makefile.include
