#define PLATFORM_LINUX_SDDS_IFACE					"wlan0"
#define PLATFORM_LINUX_SDDS_IP_ADDRESS 				"127.0.0.1"
#define PLATFORM_LINUX_SDDS_LISTEN_ADDRESS			PLATFORM_LINUX_SDDS_IP_ADDRESS"%"PLATFORM_LINUX_SDDS_IFACE
#define PLATFORM_LINUX_SDDS_SEND_ADDRESS			PLATFORM_LINUX_SDDS_IP_ADDRESS"%"PLATFORM_LINUX_SDDS_IFACE
#define PLATFORM_LINUX_SDDS_PROTOCOL				AF_INET
