JACKDAW = fe80::12:13ff:fe14:1516
BOARD = fe80::250:c2ff:ff18:86b0
#CONTIKI = $(shell echo $$HOME)/es-projekt/contiki
CONTIKI = ../../../platform/contiki

APPLICATION_NAME := mywrite

all:
	$(MAKE) -f Makefile BUILD=linux $(APPLICATION_NAME) $(MAKEOPTS) \
	                    PLATFORM_LINUX_SDDS_LISTEN_ADDRESS="$(JACKDAW)%usb0" \
	                    PLATFORM_LINUX_SDDS_SEND_ADDRESS="$(BOARD)%usb0"\
			    PLATFORM_LINUX_SDDS_PROTOCOL=AF_INET6


clean:
	$(MAKE) -f Makefile BUILD=linux clean
