JACKDAW = fe80::12:13ff:fe14:1516
BOARD = fe80::00ff:fe00:0001
#CONTIKI = $(shell echo $$HOME)/es-projekt/contiki
CONTIKI = ../../../platform/contiki

APPLICATION_NAME := mywrite

all:
	$(MAKE) -f Makefile BUILD=linux $(APPLICATION_NAME) $(MAKEOPTS) \
	                    SDDS_LINUX_LISTEN_ADDRESS="$(JACKDAW)%usb0" \
	                    SDDS_LINUX_SEND_ADDRESS="$(BOARD)%usb0"


clean:
	$(MAKE) -f Makefile BUILD=linux clean
