JACKDAW = fe80::12:13ff:fe14:1516
BOARD = fe80::00ff:fe00:0001
#CONTIKI = $(shell echo $$HOME)/es-projekt/contiki
CONTIKI = ../../../platform/contiki

APPLICATION_NAME := mywrite

all:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board $(APPLICATION_NAME).hex $(MAKEOPTS) \
	                    USE_DERFMEGA128=1 \
	                    SDDS_CONTIKI_SEND_ADDRESS="$(JACKDAW)" \
			    UIP_CONF_RPL=0

flash:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board flash $(MAKEOPTS)

debug:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board debug $(MAKEOPTS)

clean:
	$(MAKE) -f Makefile CONTIKI=$(CONTIKI) BUILD=sensor_board clean
