#define _MULTICAST
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED

#define SDDS_NET_MAX_BUF_SIZE						256

#define SDDS_NET_MAX_LOCATOR_COUNT 					20
#define SDDS_DISCOVERY_RECEIVE_TIMER				1
#define SDDS_DISCOVERY_PARTICIPANT_TIMER			10
#define SDDS_DISCOVERY_PUBLICATION_TIMER			60
#define SDDS_DISCOVERY_TOPIC_TIMER					0

#define PLATFORM_LINUX_SDDS_IFACE					"usb1"
#define PLATFORM_LINUX_SDDS_IP_ADDRESS 				"fe80::12:13ff:fe14:1516"
#define PLATFORM_LINUX_SDDS_LISTEN_ADDRESS			PLATFORM_LINUX_SDDS_IP_ADDRESS"%"PLATFORM_LINUX_SDDS_IFACE
#define PLATFORM_LINUX_SDDS_SEND_ADDRESS			PLATFORM_LINUX_SDDS_IP_ADDRESS"%"PLATFORM_LINUX_SDDS_IFACE

#define SDDS_BUILTIN_MULTICAST_ADDRESS				"ff02::10"
#define SDDS_BUILTIN_PARTICIPANT_ADDRESS			"ff02::20"
#define SDDS_BUILTIN_SUB_PUB_ADDRESS				"ff02::30"
#define SDDS_BUILTIN_TOPIC_ADDRESS					"ff02::50"

#define PLATFORM_LINUX_SDDS_PROTOCOL				AF_INET6
#define PLATFORM_LINUX_SDDS_PORT					23234
