JACKDAW = fe80::50:c4ff:fe04:2e3
BOARD = fe80::50:c4ff:fe04:81a5
#CONTIKI = $(shell echo $$HOME)/es-projekt/contiki
CONTIKI = ../../../platform/contiki

APPLICATION_NAME := mywrite

all:
	$(MAKE) -f Makefile BUILD=linux $(APPLICATION_NAME) $(MAKEOPTS) \
	                    SDDS_LINUX_LISTEN_ADDRESS="$(JACKDAW)%usb0" \
	                    SDDS_LINUX_SEND_ADDRESS="$(BOARD)%usb0"


clean:
	$(MAKE) -f Makefile BUILD=linux clean
