all:
	$(MAKE) -C sdds1 -f ../Makefile sdds $(MAKEOPTS) \
	                    SDDS_LINUX_LISTEN_ADDRESS="127.0.0.1" \
	                    SDDS_LINUX_SEND_ADDRESS="127.0.0.1" \
			    SDDS_LINUX_PROTOCOL=AF_INET
	$(MAKE) -C sdds2 -f ../Makefile sdds $(MAKEOPTS) \
	                    SDDS_LINUX_LISTEN_ADDRESS="::2" \
	                    SDDS_LINUX_SEND_ADDRESS="::1"


clean:
	$(MAKE) -C sdds1 -f ../Makefile clean
	$(MAKE) -C sdds2 -f ../Makefile clean
