#define FEATURE_SDDS_MULTICAST_ENABLED
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED
#define SDDS_HAS_QOS_RELIABILITY

#define SDDS_NET_MAX_BUF_SIZE						256
#define SDDS_NET_MAX_LOCATOR_COUNT 					10
#define SDDS_DISCOVERY_RECEIVE_TIMER				1
#define SDDS_DISCOVERY_PARTICIPANT_TIMER			10
#define SDDS_DISCOVERY_PUBLICATION_TIMER			20
#define SDDS_DISCOVERY_TOPIC_TIMER					0

