#ifndef FEATURE_SDDS_MULTICAST_ENABLED
#define FEATURE_SDDS_MULTICAST_ENABLED
#endif
#ifndef FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#endif
#ifndef FEATURE_SDDS_DISCOVERY_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED
#endif
#ifndef SDDS_HAS_QOS_RELIABILITY
#define SDDS_HAS_QOS_RELIABILITY
#endif
#ifndef SDDS_NET_MAX_BUF_SIZE
#define SDDS_NET_MAX_BUF_SIZE 8192
#endif
#ifndef SDDS_NET_MAX_LOCATOR_COUNT
#define SDDS_NET_MAX_LOCATOR_COUNT 20
#endif
#ifndef SDDS_DISCOVERY_RECEIVE_TIMER
#define SDDS_DISCOVERY_RECEIVE_TIMER 1
#endif
#ifndef SDDS_DISCOVERY_PARTICIPANT_TIMER
#define SDDS_DISCOVERY_PARTICIPANT_TIMER 1
#endif
#ifndef SDDS_DISCOVERY_PUBLICATION_TIMER
#define SDDS_DISCOVERY_PUBLICATION_TIMER 5
#endif
#ifndef SDDS_DISCOVERY_TOPIC_TIMER
#define SDDS_DISCOVERY_TOPIC_TIMER 0
#endif
