#define PLATFORM_RTOS_SDDS_IFACE					"usb0"
#define PLATFORM_RTOS_SDDS_IP_ADDRESS 				"192.168.0.1"
#define PLATFORM_RTOS_SDDS_LISTEN_ADDRESS			PLATFORM_RTOS_SDDS_IP_ADDRESS"%"PLATFORM_RTOS_SDDS_IFACE
#define PLATFORM_RTOS_SDDS_SEND_ADDRESS				PLATFORM_RTOS_SDDS_IP_ADDRESS"%"PLATFORM_RTOS_SDDS_IFACE

#define PLATFORM_RTOS_SDDS_PROTOCOL					AF_INET6
#define PLATFORM_RTOS_SDDS_PORT						23234

#define HW_ADDR0									0xE1
#define HW_ADDR1									0x00
#define HW_ADDR2									0x00
#define HW_ADDR3									0x00
#define HW_ADDR4									0x42
#define HW_ADDR5									0x42

#define _MULTICAST
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED

#define SDDS_NET_MAX_LOCATOR_COUNT 					20
#define SDDS_DISCOVERY_RECEIVE_TIMER				1
#define SDDS_DISCOVERY_PARTICIPANT_TIMER			10
#define SDDS_DISCOVERY_PUBLICATION_TIMER			60
#define SDDS_DISCOVERY_TOPIC_TIMER					0

#define SDDS_BUILTIN_MULTICAST_ADDRESS				"ff02::10"
#define SDDS_BUILTIN_PARTICIPANT_ADDRESS			"ff02::20"
#define SDDS_BUILTIN_SUB_PUB_ADDRESS				"ff02::30"
#define SDDS_BUILTIN_TOPIC_ADDRESS					"ff02::50"
